WiseCrackCollector/ViewModels/GroupMembersViewModel.cs
using WiseCrackCollector.Models;

namespace WiseCrackCollector.ViewModels
{
    public class GroupMembersViewModel
    {
        public Group Group { get; set; }
        public List<AppUser> NotMemberUsers { get; set; }
        public List<GroupUserMembership> Memberships { get; set; }
    }
}

WiseCrackCollector/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WiseCrackCollector.Models;
using WiseCrackCollector.Services;
using WiseCrackCollector.ViewModels;

namespace WiseCrackCollector.Controllers
{
    public class GroupsController : Controller
    {
        private IGroupService groupService;
        private IWisecrackService wisecrackService;
        private IMemberService memberService;
        private IAppUserService appUserService;

        public GroupsController(IGroupService _groupService, IWisecrackService _wisecrackService, IMemberService _memberService, IAppUserService _appUserService)
        {
            groupService = _groupService;
            wisecrackService = _wisecrackService;
            memberService = _memberService;
            appUserService = _appUserService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [Route("/Groups/MyGroups")]
        public IActionResult MyGroups()
        {
            List<Group> groups = groupService.GetGroupsOwnedByCurrentUser();
            Response.Cookies.Append("redirectTo", "MyGroups");
            return View(groups);
        }

        [Authorize]
        [Route("/Groups/MyMemberships")]
        public IActionResult MyMemberships()
        {
            List<Group> groups = groupService.GetGroupsConnectedToCurrentUser();
            Response.Cookies.Append("redirectTo", "MyMemberships");
            return View(groups);
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/New")]
        public IActionResult New(string new_group_name)
        {
            string newGroupId = groupService.CreateGroup(new_group_name);
            string userId = appUserService.GetCurrentUser().Id;
            GroupUserMembership groupUserMembership = new GroupUserMembership(userId, newGroupId)
            {
                Read = true,
                Add = true,
                Update = true,
                Delete = true,
                ManageMembers = true
            };
            memberService.AddMember(groupUserMembership);
            return RedirectToAction("Details", new { groupId = newGroupId });
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/Delete")]
        public IActionResult Delete(string delete_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(delete_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(delete_group_id, PermissionType.Delete, out membership))
                return Forbid();

            wisecrackService.DeleteWisecracksByGroupId(delete_group_id);
            groupService.DeleteGroup(delete_group_id);

            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [HttpPost]

        [Route("/Groups/Empty")]
        public IActionResult Empty(string empty_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(empty_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(empty_group_id, PermissionType.Delete, out membership))
                return Forbid();

            wisecrackService.DeleteWisecracksByGroupId(empty_group_id);

            return RedirectToAction("Details", new { groupId = empty_group_id });
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/Update")]
        public IActionResult Update(string edit_group_id, string edit_group_name)
        {
            // check if group exists
            if (!groupService.IsGroupExists(edit_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(edit_group_id, PermissionType.Update, out membership))
                return Forbid();

            groupService.EditGroup(edit_group_id, edit_group_name);

            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [Route("/Groups/{groupId}")]
        public IActionResult Details(string groupId)
        {
            string redirectTo = "MyGroups";
            if (Request.Cookies.ContainsKey("redirectTo"))
                redirectTo = Request.Cookies["redirectTo"];

            // check if group exists
            if (!groupService.IsGroupExists(groupId))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(groupId, PermissionType.Read, out membership))
                return Forbid();

            Group group = groupService.GetGroupById(groupId);
            List<Wisecrack> wisecracks = wisecrackService.GetWisecracksByGroupId(groupId);

            // Create view model
            GroupViewModel groupViewModel = new GroupViewModel()
            {
                Group = group,
                Wisecracks = wisecracks,
                Permissions = membership,
                RedirectAction = redirectTo == "MyMemberships" ? "MyMemberships" : "MyGroups",
                RedirectTitle = redirectTo == "MyMemberships" ? "Memberships" : "My Groups"
            };

            return View(groupViewModel);
        }
    }
}

WiseCrackCollector/Controllers/MembersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using WiseCrackCollector.Models;
using WiseCrackCollector.Services;
using WiseCrackCollector.ViewModels;

namespace WiseCrackCollector.Controllers
{
    public class MembersController : Controller
    {

        private IMemberService memberService;
        private IGroupService groupService;
        private IAppUserService appUserService;

        public MembersController(IMemberService _memberService, IGroupService _groupService, IAppUserService _appUserService)
        {
            memberService = _memberService;
            groupService = _groupService;
            appUserService = _appUserService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("/Members/GroupMembers")]
        public IActionResult GroupMembers(string groupId)
        {
            // check if group exists
            if (!groupService.IsGroupExists(groupId))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(groupId, PermissionType.ManageMembers, out membership))
                return Forbid();

            Group group = groupService.GetGroupById(groupId);
            List<GroupUserMembership> memberships = memberService.GetMembershipsByGroupId(groupId);
            List<AppUser> allUsers = appUserService.GetAppUsers();
            AppUser currentUser = appUserService.GetCurrentUser();

            List<AppUser> NotMemberUsers = allUsers.Where(i => !i.Id.Equals(currentUser.Id) && !memberships.Any(m => m.UserId.Equals(i.Id))).ToList();

            GroupMembersViewModel groupMembersViewModel = new GroupMembersViewModel()
            {
                Group = group,
                NotMemberUsers = NotMemberUsers,
                Memberships = memberships
            };

            return View(groupMembersViewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(string new_member_group_id, string new_member_user_id, string new_member_perm_add, string new_member_perm_read, string new_member_perm_update, string new_member_perm_delete, string new_member_perm_members)
        {
            GroupUserMembership groupUserMembership = new GroupUserMembership(new_member_user_id, new_member_group_id)
            {
                Add = !string.IsNullOrEmpty(new_member_perm_add),
                Read = !string.IsNullOrEmpty(new_member_perm_read),
                Update = !string.IsNullOrEmpty(new_member_perm_update),
                Delete = !string.IsNullOrEmpty(new_member_perm_delete),
                ManageMembers = !string.IsNullOrEmpty(new_member_perm_members)
            };
            memberService.AddMember(groupUserMembership);
            return RedirectToAction("GroupMembers", new { groupId = new_member_group_id });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(string delete_member_user_id, string delete_member_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(delete_member_group_id))
                return NotFound();

            // check if membership exists
            if (!memberService.IsMembershipExists(delete_member_group_id, delete_member_user_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(delete_member_group_id, PermissionType.ManageMembers, out membership))
                return Forbid();

            memberService.DeleteMembership(delete_member_group_id, delete_member_user_id);

            return RedirectToAction("GroupMembers", new { groupId = delete_member_group_id });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Update(string edit_membership_group_id, string edit_membership_user_id, string edit_membership_perm_add, string edit_membership_perm_read, string edit_membership_perm_update, string edit_membership_perm_delete, string edit_membership_perm_members)
        {
            // check if group exists
            if (!groupService.IsGroupExists(edit_membership_group_id))
                return NotFound();

            // check if membership exists
            if (!memberService.IsMembershipExists(edit_membership_group_id, edit_membership_user_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership currentUserPermissions;
            if (!groupService.CheckPermissionOnGroup(edit_membership_group_id, PermissionType.ManageMembers, out currentUserPermissions))
                return Forbid();

            // Update membership
            GroupUserMembership membership = memberService.GetGroupUserMembershipById(edit_membership_group_id, edit_membership_user_id);
            membership.Add = !string.IsNullOrEmpty(edit_membership_perm_add);
            membership.Read = !string.IsNullOrEmpty(edit_membership_perm_read);
            membership.Update = !string.IsNullOrEmpty(edit_membership_perm_update);
            membership.Delete = !string.IsNullOrEmpty(edit_membership_perm_delete);
            membership.ManageMembers = !string.IsNullOrEmpty(edit_membership_perm_members);
            memberService.UpdateMembership(membership);

            return RedirectToAction("GroupMembers", new { groupId = edit_membership_group_id });
        }
    }
}

WiseCrackCollector/Views/Members/GroupMembers.cshtml
@model GroupMembersViewModel
@using System.Web

<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

<h1>Members of group: @Model.Group.Name</h1>

<div class="row menu-row">
    <div class="col">
        <form asp-controller="Groups" asp-action="Details" asp-route-groupId="@Model.Group.Id" method="post" style="display: inline;">
            <button type="submit" class="btn btn-outline-dark">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8" />
                </svg>
                Group
            </button>
        </form>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAddMember">
            Add Member
        </button>
    </div>
</div>

<!-- Add Member Modal -->
<div class="modal" id="modalAddMember">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add Member</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="addMemberForm" asp-controller="Members" asp-action="Add" method="post">
                <input type="hidden" name="new_member_group_id" value="@Model.Group.Id" />
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="new_member_id" class="col-form-label">New member:</label>
                        <select name="new_member_user_id">
                            @foreach (AppUser user in Model.NotMemberUsers)
                            {
                                <option value="@user.Id">@user.UserName (@user.Email)</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Permissions:</label>
                        <div class="form-check">
                            <input type="checkbox" name="new_member_perm_add" id="new_member_perm_add" class="form-check-input" />
                            <label class="form-class-label" for="new_member_perm_add">Add</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="new_member_perm_read" id="new_member_perm_read" class="form-check-input" />
                            <label class="form-class-label" for="new_member_perm_read">Read</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="new_member_perm_update" id="new_member_perm_update" class="form-check-input" />
                            <label class="form-class-label" for="new_member_perm_update">Update</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="new_member_perm_delete" id="new_member_perm_delete" class="form-check-input" />
                            <label class="form-class-label" for="new_member_perm_delete">Delete</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="new_member_perm_members" id="new_member_perm_members" class="form-check-input" />
                            <label class="form-class-label" for="new_member_perm_members">Manage members</label>
                        </div>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Add" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Membership Modal -->
<div class="modal" id="modalEditMembership">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Membership</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="editMembershipForm" asp-controller="Members" asp-action="Update" method="post">
                <input type="hidden" name="edit_membership_group_id" value="@Model.Group.Id" />
                <input type="hidden" id="edit_membership_user_id" name="edit_membership_user_id" />
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="edit_membership_user_name" class="col-form-label">Member:</label>
                        <span name="edit_membership_user_name" id="edit_membership_user_name"></span>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Permissions:</label>
                        <div class="form-check">
                            <input type="checkbox" name="edit_membership_perm_add" id="edit_membership_perm_add" class="form-check-input" />
                            <label class="form-class-label" for="edit_membership_perm_add">Add</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="edit_membership_perm_read" id="edit_membership_perm_read" class="form-check-input" />
                            <label class="form-class-label" for="edit_membership_perm_read">Read</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="edit_membership_perm_update" id="edit_membership_perm_update" class="form-check-input" />
                            <label class="form-class-label" for="edit_membership_perm_update">Update</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="edit_membership_perm_delete" id="edit_membership_perm_delete" class="form-check-input" />
                            <label class="form-class-label" for="edit_membership_perm_delete">Delete</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="edit_membership_perm_members" id="edit_membership_perm_members" class="form-check-input" />
                            <label class="form-class-label" for="edit_membership_perm_members">Manage members</label>
                        </div>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Update" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Membership Modal -->
<div class="modal" id="modalDeleteMembership">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Remove Member</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="deleteMembershipForm" asp-controller="Members" asp-action="Delete" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Are you sure you want to remove <span id="delete_member_user_name"></span> from the group?</label>
                        <input type="hidden" name="delete_member_group_id" value="@Model.Group.Id" />
                        <input type="hidden" id="delete_member_user_id" name="delete_member_user_id" />
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" value="Remove" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<h3 class="list-title">Member List</h3>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th class="text-center">Read</th>
            <th class="text-center">Add</th>
            <th class="text-center">Update</th>
            <th class="text-center">Delete</th>
            <th class="text-center">Manage<br />Members</th>
            <th>Joined At</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var membership in Model.Memberships)
        {
            <tr>
                <td>@membership.User.UserName</td>
                <td class="text-center"><input type="checkbox" class="form-check-input" checked="@membership.Read" disabled /></td>
                <td class="text-center"><input type="checkbox" class="form-check-input" checked="@membership.Add" disabled /></td>
                <td class="text-center"><input type="checkbox" class="form-check-input" checked="@membership.Update" disabled /></td>
                <td class="text-center"><input type="checkbox" class="form-check-input" checked="@membership.Delete" disabled /></td>
                <td class="text-center"><input type="checkbox" class="form-check-input" checked="@membership.ManageMembers" disabled /></td>
                <td>@membership.JoinedAt.ToString("yyyy.MM.dd")</td>
                <td>
                    <button type="button" class="btn btn-outline-warning" data-toggle="modal" data-target="#modalEditMembership" onclick="SetMembershipEditorData('@membership.UserId', '@HttpUtility.HtmlEncode(membership.User.UserName)', '@membership.Read', '@membership.Add', '@membership.Update', '@membership.Delete', '@membership.ManageMembers')">
                        Permissions
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#modalDeleteMembership" onclick="SetMembershipDeleteData('@membership.UserId', '@HttpUtility.HtmlEncode(membership.User.UserName)')">
                        Remove
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

WiseCrackCollector/Views/Members/Manage.cshtml
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var wisecrack in Model.Wisecracks)
        {
            <tr>
                <td>@wisecrack.SaidBy</td>
                <td>@wisecrack.Content</td>
                <td>@wisecrack.Views</td>
                <td>@wisecrack.CreatedAt.ToString("yyyy.MM.dd")</td>
                <td class="text-end">
                    @if (Model.Permissions.Update)
                    {
                        string addedAt = wisecrack.CreatedAt.ToString("yyyy-MM-dd");
                        <button type="button" class="btn btn-outline-warning" data-toggle="modal" data-target="#modalEditWisecrack" onclick="SetWisecrackEditorData('@wisecrack.Id', '@wisecrack.SaidBy', '@wisecrack.Content', '@addedAt');">
                            Edit
                        </button>
                    }
                    @if (Model.Permissions.Delete)
                    {
                        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#modalDeleteWisecrack" onclick="SetWisecrackDeleteID('@wisecrack.Id')">
                            Delete
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>