WiseCrackCollector/Models/Group.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WiseCrackCollector.Models
{
    [Table("Groups")]
    public class Group
    {
        [Key, StringLength(100)]
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [Required, StringLength(100)]
        public string Name { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public List<Wisecrack> Wisecracks = new List<Wisecrack>();

        [Required, ForeignKey("OwnerId")]
        public AppUser Owner { get; set; }

        public List<GroupUserMembership> Memberships;
    }
}

WiseCrackCollector/Models/GroupViewModel.cs
namespace WiseCrackCollector.Models
{
    public enum WisecrackListSortBy
    {
        Author,
        Content,
        Views,
        Date,
        None
    }

    public enum WisecrackListSortOrder
    {
        Ascending,
        Descending
    }

    public class GroupViewModel
    {
        public Group Group { get; set; }
        public List<Wisecrack> Wisecracks { get; set; }
        public UserGroupPermissionSet Permissions { get; set; }
        public WisecrackListSortBy SortBy { get; set; }
        public WisecrackListSortOrder SortOrder { get; set; }
    }
}

WiseCrackCollector/ViewModels/GroupViewModel.cs
using WiseCrackCollector.Models;

namespace WiseCrackCollector.ViewModels
{
    public class GroupViewModel
    {
        public Group Group { get; set; }
        public List<Wisecrack> Wisecracks { get; set; }
        public GroupUserMembership Permissions { get; set; }
        public string RedirectController {  get; set; }
        public string RedirectAction { get; set; }
        public string RedirectTitle { get; set; }
    }
}

WiseCrackCollector/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WiseCrackCollector.Models;
using WiseCrackCollector.Services;
using WiseCrackCollector.ViewModels;

namespace WiseCrackCollector.Controllers
{
    public class GroupsController : Controller
    {
        private IGroupService groupService;
        private IWisecrackService wisecrackService;
        private IMemberService memberService;
        private IAppUserService appUserService;

        public GroupsController(IGroupService _groupService, IWisecrackService _wisecrackService, IMemberService _memberService, IAppUserService _appUserService)
        {
            groupService = _groupService;
            wisecrackService = _wisecrackService;
            memberService = _memberService;
            appUserService = _appUserService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [Route("/Groups/MyGroups")]
        public IActionResult MyGroups()
        {
            List<Group> groups = groupService.GetGroupsOwnedByCurrentUser();
            Response.Cookies.Append("redirectTo", "MyGroups");
            return View(groups);
        }

        [Authorize]
        [Route("/Groups/MyMemberships")]
        public IActionResult MyMemberships()
        {
            List<Group> groups = groupService.GetGroupsConnectedToCurrentUser();
            Response.Cookies.Append("redirectTo", "MyMemberships");
            return View(groups);
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/New")]
        public IActionResult New(string new_group_name)
        {
            string newGroupId = groupService.CreateGroup(new_group_name);
            string userId = appUserService.GetCurrentUser().Id;
            GroupUserMembership groupUserMembership = new GroupUserMembership(userId, newGroupId)
            {
                Read = true,
                Add = true,
                Update = true,
                Delete = true,
                ManageMembers = true
            };
            memberService.AddMember(groupUserMembership);
            return RedirectToAction("Details", new { groupId = newGroupId });
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/Delete")]
        public IActionResult Delete(string delete_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(delete_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(delete_group_id, PermissionType.Delete, out membership))
                return Forbid();

            wisecrackService.DeleteWisecracksByGroupId(delete_group_id);
            groupService.DeleteGroup(delete_group_id);

            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [HttpPost]

        [Route("/Groups/Empty")]
        public IActionResult Empty(string empty_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(empty_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(empty_group_id, PermissionType.Delete, out membership))
                return Forbid();

            wisecrackService.DeleteWisecracksByGroupId(empty_group_id);

            return RedirectToAction("Details", new { groupId = empty_group_id });
        }

        [Authorize]
        [HttpPost]
        [Route("/Groups/Update")]
        public IActionResult Update(string edit_group_id, string edit_group_name)
        {
            // check if group exists
            if (!groupService.IsGroupExists(edit_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(edit_group_id, PermissionType.Update, out membership))
                return Forbid();

            groupService.EditGroup(edit_group_id, edit_group_name);

            return RedirectToAction("MyGroups");
        }

        [Authorize]
        [Route("/Groups/{groupId}")]
        public IActionResult Details(string groupId)
        {
            string redirectTo = "MyGroups";
            if (Request.Cookies.ContainsKey("redirectTo"))
                redirectTo = Request.Cookies["redirectTo"];

            // check if group exists
            if (!groupService.IsGroupExists(groupId))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(groupId, PermissionType.Read, out membership))
                return Forbid();

            Group group = groupService.GetGroupById(groupId);
            List<Wisecrack> wisecracks = wisecrackService.GetWisecracksByGroupId(groupId);

            // Create view model
            GroupViewModel groupViewModel = new GroupViewModel()
            {
                Group = group,
                Wisecracks = wisecracks,
                Permissions = membership,
                RedirectAction = redirectTo == "MyMemberships" ? "MyMemberships" : "MyGroups",
                RedirectTitle = redirectTo == "MyMemberships" ? "Memberships" : "My Groups"
            };

            return View(groupViewModel);
        }
    }
}

WiseCrackCollector/Controllers/MembersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using WiseCrackCollector.Models;
using WiseCrackCollector.Services;
using WiseCrackCollector.ViewModels;

namespace WiseCrackCollector.Controllers
{
    public class MembersController : Controller
    {

        private IMemberService memberService;
        private IGroupService groupService;
        private IAppUserService appUserService;

        public MembersController(IMemberService _memberService, IGroupService _groupService, IAppUserService _appUserService)
        {
            memberService = _memberService;
            groupService = _groupService;
            appUserService = _appUserService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("/Members/GroupMembers")]
        public IActionResult GroupMembers(string groupId)
        {
            // check if group exists
            if (!groupService.IsGroupExists(groupId))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(groupId, PermissionType.ManageMembers, out membership))
                return Forbid();

            Group group = groupService.GetGroupById(groupId);
            List<GroupUserMembership> memberships = memberService.GetMembershipsByGroupId(groupId);
            List<AppUser> allUsers = appUserService.GetAppUsers();
            AppUser currentUser = appUserService.GetCurrentUser();

            List<AppUser> NotMemberUsers = allUsers.Where(i => !i.Id.Equals(currentUser.Id) && !memberships.Any(m => m.UserId.Equals(i.Id))).ToList();

            GroupMembersViewModel groupMembersViewModel = new GroupMembersViewModel()
            {
                Group = group,
                NotMemberUsers = NotMemberUsers,
                Memberships = memberships
            };

            return View(groupMembersViewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(string new_member_group_id, string new_member_user_id, string new_member_perm_add, string new_member_perm_read, string new_member_perm_update, string new_member_perm_delete, string new_member_perm_members)
        {
            GroupUserMembership groupUserMembership = new GroupUserMembership(new_member_user_id, new_member_group_id)
            {
                Add = !string.IsNullOrEmpty(new_member_perm_add),
                Read = !string.IsNullOrEmpty(new_member_perm_read),
                Update = !string.IsNullOrEmpty(new_member_perm_update),
                Delete = !string.IsNullOrEmpty(new_member_perm_delete),
                ManageMembers = !string.IsNullOrEmpty(new_member_perm_members)
            };
            memberService.AddMember(groupUserMembership);
            return RedirectToAction("GroupMembers", new { groupId = new_member_group_id });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(string delete_member_user_id, string delete_member_group_id)
        {
            // check if group exists
            if (!groupService.IsGroupExists(delete_member_group_id))
                return NotFound();

            // check if membership exists
            if (!memberService.IsMembershipExists(delete_member_group_id, delete_member_user_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(delete_member_group_id, PermissionType.ManageMembers, out membership))
                return Forbid();

            memberService.DeleteMembership(delete_member_group_id, delete_member_user_id);

            return RedirectToAction("GroupMembers", new { groupId = delete_member_group_id });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Update(string edit_membership_group_id, string edit_membership_user_id, string edit_membership_perm_add, string edit_membership_perm_read, string edit_membership_perm_update, string edit_membership_perm_delete, string edit_membership_perm_members)
        {
            // check if group exists
            if (!groupService.IsGroupExists(edit_membership_group_id))
                return NotFound();

            // check if membership exists
            if (!memberService.IsMembershipExists(edit_membership_group_id, edit_membership_user_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership currentUserPermissions;
            if (!groupService.CheckPermissionOnGroup(edit_membership_group_id, PermissionType.ManageMembers, out currentUserPermissions))
                return Forbid();

            // Update membership
            GroupUserMembership membership = memberService.GetGroupUserMembershipById(edit_membership_group_id, edit_membership_user_id);
            membership.Add = !string.IsNullOrEmpty(edit_membership_perm_add);
            membership.Read = !string.IsNullOrEmpty(edit_membership_perm_read);
            membership.Update = !string.IsNullOrEmpty(edit_membership_perm_update);
            membership.Delete = !string.IsNullOrEmpty(edit_membership_perm_delete);
            membership.ManageMembers = !string.IsNullOrEmpty(edit_membership_perm_members);
            memberService.UpdateMembership(membership);

            return RedirectToAction("GroupMembers", new { groupId = edit_membership_group_id });
        }
    }
}

WiseCrackCollector/Controllers/WisecracksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WiseCrackCollector.Models;
using WiseCrackCollector.Services;

namespace WiseCrackCollector.Controllers
{
    public class WisecracksController : Controller
    {
        private IWisecrackService wisecrackService;
        private IGroupService groupService;

        public WisecracksController(IWisecrackService _wisecrackService, IGroupService _groupService)
        {
            wisecrackService = _wisecrackService;
            groupService = _groupService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("/Wisecracks/Add")]
        public IActionResult Add(string new_wc_group_id, string new_wc_content, string? new_wc_saidBy)
        {
            // check if group exists
            if (!groupService.IsGroupExists(new_wc_group_id))
                return NotFound();

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(new_wc_group_id, PermissionType.Add, out membership))
                return Forbid();

            Wisecrack newWisecrack = new Wisecrack()
            {
                Content = new_wc_content,
                SaidBy = new_wc_saidBy == null ? "unknown" : new_wc_saidBy
            };

            wisecrackService.AddWisecrack(new_wc_group_id, newWisecrack);

            return RedirectToAction("Details", "Groups", new { groupId = new_wc_group_id });
        }

        [Authorize]
        [HttpPost]
        [Route("/Wisecracks/Delete")]
        public IActionResult Delete(string delete_wc_id)
        {
            // check if wisecrack exists
            if (!wisecrackService.IsWisecrackExists(delete_wc_id))
                return NotFound();

            Wisecrack wisecrack = wisecrackService.GetWisecrackById(delete_wc_id);

            // Check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(wisecrack.Group.Id, PermissionType.Delete, out membership))
                return Forbid();

            wisecrackService.DeleteWisecrack(wisecrack);

            return RedirectToAction("Details", "Groups", new { groupId = wisecrack.Group.Id });
        }

        [Authorize]
        [HttpPost]
        [Route("/Wisecracks/Update")]
        public IActionResult Update(string edit_wc_id, string edit_wc_saidBy, string edit_wc_content, string edit_wc_date)
        {
            // check if wisecrack exists
            if (!wisecrackService.IsWisecrackExists(edit_wc_id))
                return NotFound();

            Wisecrack wisecrack = wisecrackService.GetWisecrackById(edit_wc_id);

            // check if the user has enough permission
            GroupUserMembership membership;
            if (!groupService.CheckPermissionOnGroup(wisecrack.Group.Id, PermissionType.Update, out membership))
                return Forbid();

            if (string.IsNullOrEmpty(edit_wc_content))
                return BadRequest();
            if (string.IsNullOrEmpty(edit_wc_saidBy))
                edit_wc_saidBy = "unknown";
            

            wisecrack.Content = edit_wc_content;
            wisecrack.CreatedAt = DateTime.Parse(edit_wc_date);
            wisecrack.SaidBy = edit_wc_saidBy;

            wisecrackService.UpdateWisecrack(wisecrack);

            return RedirectToAction("Details", "Groups", new { groupId = wisecrack.Group.Id });
        }
    }
}

WiseCrackCollector/Views/Groups/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using WiseCrackCollector.ViewModels
@model GroupViewModel

<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>



<h1>Group: @Model.Group.Name</h1>

<!-- Buttons -->
<div class="row menu-row">
    <div class="col">
        <form asp-controller="Groups" asp-action="@Model.RedirectAction" method="post" style="display: inline;">
            <button type="submit" class="btn btn-outline-dark">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8" />
                </svg>
                @Model.RedirectTitle
            </button>
        </form>
        @if (Model.Permissions.Add)
        {
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalNewWisecrack">
                Add Wisecrack
            </button>
        }
        @if (Model.Permissions.Delete)
        {
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDeleteGroup">
                Delete Group
            </button>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalEmptyGroup">
                Empty Group
            </button>
        }
        @if (Model.Permissions.ManageMembers)
        {
            <form asp-controller="Members" asp-action="GroupMembers" asp-route-groupId="@Model.Group.Id" style="display: inline;">
                <button type="submit" class="btn btn-outline-dark">
                    Members
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                        <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                    </svg>
                </button>
            </form>
        }
    </div>
</div>

<!-- Delete Group Modal -->
<div class="modal" id="modalDeleteGroup">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Delete Group</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="deleteGroupForm" asp-controller="Groups" asp-action="Delete" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Are you sure you want to delete this group, including all the wisecracks in it?</label>
                        <input type="hidden" name="delete_group_id" value="@Model.Group.Id" />
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" value="Delete" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete All Wisecracks Modal -->
<div class="modal" id="modalEmptyGroup">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Empty Group</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="emptyGroupForm" asp-controller="Groups" asp-action="Empty" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Are you sure you want to delete all wisecracks in this group?</label>
                        <input type="hidden" name="empty_group_id" value="@Model.Group.Id" />
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" value="Delete"/>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- New Wiscrack Modal -->
<div class="modal" id="modalNewWisecrack">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add New Wisecrack</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="newWisecrackForm" asp-controller="Wisecracks" asp-action="Add" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="new_wc_group" class="col-form-label">Group:</label>
                        <input type="text" name="wc_group" class="form-control" id="wc_group" value="@Model.Group.Name" readonly>
                        <input type="hidden" name="new_wc_group_id" value="@Model.Group.Id" />
                    </div>
                    <div class="form-group">
                        <label for="new_wc_saidBy" class="col-form-label">Who said it? (optional)</label>
                        <input type="text" name="new_wc_saidBy" class="form-control" id="new_wc_saidBy">
                    </div>
                    <div class="form-group">
                        <label for="new_wc_content" class="col-form-label">Wisecrack:</label>
                        <input type="text" name="new_wc_content" class="form-control" id="new_wc_content" required>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Add" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<partial name="/Views/Shared/WisecrackListModule.cshtml" />

WiseCrackCollector/Views/Groups/MyGroups.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Web
@model List<Group>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


<h1>My Groups</h1>

<div class="row menu-row">
    <div class="col">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalNewGroup">
            New Group
        </button>
    </div>
</div>

<!-- New Group Modal -->
<div class="modal" id="modalNewGroup">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">New Group</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="newGroupForm" asp-controller="Groups" asp-action="New" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="new_group_owner" class="col-form-label">Owner:</label>
                        <input type="text" name="new_group_owner" class="form-control" id="new_group_owner" value="@User.Identity?.Name" readonly>
                    </div>
                    <div class="form-group">
                        <label for="new_group_name" class="col-form-label">Group name:</label>
                        <input type="text" name="new_group_name" class="form-control" id="new_group_name" minlength="3" maxlength="100">
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Create" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Group Modal -->
<div class="modal" id="modalDeleteGroup">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Delete Group</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="deleteGroupForm" asp-controller="Groups" asp-action="Delete" method="post">
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Are you sure you want to delete the group "<span id="delete_group_name"></span>", including all the wisecracks in it?</label>
                        <input type="hidden" name="delete_group_id" id="delete_group_id" value="" />
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" value="Delete" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Group Modal -->
<div class="modal" id="modalEditGroup">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Group</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form id="editGroupForm" asp-controller="Groups" asp-action="Update" method="post">
                <!-- Modal body -->
                <input type="hidden" name="edit_group_id" id="edit_group_id" value="" />
                <div class="modal-body">
                    <div class="form-group">
                        <label for="edit_group_owner" class="col-form-label">Owner:</label>
                        <input type="text" name="edit_group_owner" class="form-control" id="edit_group_owner" value="" readonly>
                    </div>
                    <div class="form-group">
                        <label for="edit_group_name" class="col-form-label">Name:</label>
                        <input type="text" name="edit_group_name" class="form-control" id="edit_group_name" value="">
                    </div>
                    <div class="form-group">
                        <label for="edit_group_date" class="col-form-label">Date:</label>
                        <input type="text" class="form-control" name="edit_group_date" id="edit_group_date" readonly>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Modify" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- List -->
<h3 class="list-title">Group List</h3>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Owner</th>
            <th># of wisecracks</th>
            <th>Created At</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>
                    <a class="text-dark" asp-controller="Groups" asp-action="Details" asp-route-groupId="@group.Id">@group.Name</a>
                </td>
                <td>@group.Owner.UserName</td>
                <td>@group.Wisecracks.Count()</td>
                <td>@group.CreatedAt.ToString("yyyy.MM.dd")</td>
                <td class="text-end">
                    @{
                        string createdAt = group.CreatedAt.ToString("yyyy-MM-dd");
                    }
                    <button type="button" class="btn btn-outline-warning" data-toggle="modal" data-target="#modalEditGroup" onclick="SetGroupEditorData('@group.Id', '@HttpUtility.HtmlEncode(group.Name)', '@HttpUtility.HtmlEncode(group.Owner.UserName)', '@createdAt');">
                        Edit
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#modalDeleteGroup" onclick="SetGroupDeleteID('@group.Id', '@HttpUtility.HtmlEncode(group.Name)')">
                        Delete
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>